/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Entity_Client;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io. IOException;
import java.io. InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java. util.logging.Logger;
import java.io.PrintWriter;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author GARRY
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    private tickets tiket;
    private int jumlah;
    public Checkout(tickets tiket, int jumlah) {
        initComponents();
        this.tiket = tiket;
        this.jumlah = jumlah;

        double totalHarga = tiket.getHarga() * jumlah;
        jLabelTotalTiket1.setText("Rp. " + totalHarga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTotal = new javax.swing.JLabel();
        jLabelTotalTiket = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLabelFormCheckout = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNomor = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNomor = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelMetodePembayaran = new javax.swing.JLabel();
        jRadioButtonTransferBank = new javax.swing.JRadioButton();
        jRadioButtonVirtualAccount = new javax.swing.JRadioButton();
        jRadioButtonEmoney = new javax.swing.JRadioButton();
        jLabelTotal1 = new javax.swing.JLabel();
        jLabelTotalTiket1 = new javax.swing.JLabel();
        jButtonBackCheckout = new javax.swing.JButton();

        jLabelTotal.setBackground(new java.awt.Color(255, 102, 102));
        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotal.setText("Total:");
        jLabelTotal.setToolTipText("");

        jLabelTotalTiket.setText("Total");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jLabelFormCheckout.setBackground(new java.awt.Color(255, 102, 102));
        jLabelFormCheckout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelFormCheckout.setText("FORM CHECKOUT");
        jLabelFormCheckout.setToolTipText("");

        jLabelEmail.setBackground(new java.awt.Color(255, 102, 102));
        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setText("Alamat Email:");
        jLabelEmail.setToolTipText("");

        jLabelNomor.setBackground(new java.awt.Color(255, 102, 102));
        jLabelNomor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomor.setText("Nomor Telepon:");
        jLabelNomor.setToolTipText("");

        jLabelNama.setBackground(new java.awt.Color(255, 102, 102));
        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNama.setText("Nama Lengkap:");
        jLabelNama.setToolTipText("");

        jLabelMetodePembayaran.setBackground(new java.awt.Color(255, 102, 102));
        jLabelMetodePembayaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMetodePembayaran.setText("Metode Pembayaran:");
        jLabelMetodePembayaran.setToolTipText("");

        jRadioButtonTransferBank.setText("Transfer Bank");
        jRadioButtonTransferBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTransferBankActionPerformed(evt);
            }
        });

        jRadioButtonVirtualAccount.setText("Virtual Account");
        jRadioButtonVirtualAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVirtualAccountActionPerformed(evt);
            }
        });

        jRadioButtonEmoney.setText("E-Money");
        jRadioButtonEmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmoneyActionPerformed(evt);
            }
        });

        jLabelTotal1.setBackground(new java.awt.Color(255, 102, 102));
        jLabelTotal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotal1.setText("Total:");
        jLabelTotal1.setToolTipText("");

        jLabelTotalTiket1.setText("Total");

        jButtonBackCheckout.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonBackCheckout.setText("←");
        jButtonBackCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelNama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNama))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelNomor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmail)
                                            .addComponent(jLabelTotal1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldEmail)
                                            .addComponent(jLabelTotalTiket1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelMetodePembayaran)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonTransferBank, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)
                                            .addComponent(jRadioButtonVirtualAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(jRadioButtonEmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonBackCheckout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFormCheckout)
                        .addGap(106, 106, 106))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFormCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBackCheckout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTotalTiket1)))
                .addComponent(jLabelMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonVirtualAccount)
                    .addComponent(jRadioButtonEmoney)
                    .addComponent(jRadioButtonTransferBank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        String nama = jTextFieldNama.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        String nomor = jTextFieldNomor.getText().trim();
        String metode = "";

        if (jRadioButtonEmoney.isSelected()) {
            metode = "Emoney";
        } else if (jRadioButtonTransferBank.isSelected()) {
            metode = "TransferBank";
        } else if (jRadioButtonVirtualAccount.isSelected()) {
            metode = "VirtualAccount";
        }

        if (nama.isEmpty() || email.isEmpty() || nomor.isEmpty() || metode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi dan metode pembayaran harus dipilih.", "Validasi Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Socket socket = new Socket("localhost", 7000);
            PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
            BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            String request = String.format("CHECKOUT|%s|%s|%s|%s|%s|%s|%d",
                nama, email, nomor, metode,
                tiket.getNamaKonser(),
                tiket.getJenis(),
                jumlah
            );

            out.println(request);
            out.flush();

            String response = in.readLine();
            if (response != null && response.equals("CHECKOUT_SUCCESS")) {
                JOptionPane.showMessageDialog(this, "Checkout berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                String line;
                List<tickets> daftarTiket = new ArrayList<>();
                
                while ((response = in.readLine()) != null) {
                    if (response.startsWith("TICKET|")) {
                        String[] data = response.split("\\|");
                        String nama1 = data[1];
                        String jenis = data[2];
                        double harga = Double.parseDouble(data[3]);
                        int jumlah1 = Integer.parseInt(data[4]);
                        daftarTiket.add(new tickets(nama1, jenis, harga, jumlah1));
                    } else if (response.equals("END")) {
                        break;
                    }   
                }
                new ListTicket(daftarTiket).setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Checkout gagal: " + response, "Gagal", JOptionPane.ERROR_MESSAGE);
            }

            in.close();
            out.close();
            socket.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke server.", "Koneksi Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jRadioButtonTransferBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTransferBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTransferBankActionPerformed

    private void jRadioButtonVirtualAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVirtualAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVirtualAccountActionPerformed

    private void jRadioButtonEmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEmoneyActionPerformed

    private void jButtonBackCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackCheckoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tickets t = null;
                new Checkout(t, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCheckout;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFormCheckout;
    private javax.swing.JLabel jLabelMetodePembayaran;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNomor;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotal1;
    private javax.swing.JLabel jLabelTotalTiket;
    private javax.swing.JLabel jLabelTotalTiket1;
    private javax.swing.JRadioButton jRadioButtonEmoney;
    private javax.swing.JRadioButton jRadioButtonTransferBank;
    private javax.swing.JRadioButton jRadioButtonVirtualAccount;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNomor;
    // End of variables declaration//GEN-END:variables
}
